### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yusukebe** [yusukebe/hono#2]
- [x] Support wrangler2
- [x] expressjs like req/res handling
- [x] Benchmark
- [x] Try on Fastly Compute@Edge
- [x] ~~Template project of Cloudflare Workers~~ **Later**
- [x] npmignore
- [x] ~~mime-type~~
- [x] ~~`any`~~ `all`
- [x] ~~Try on Deno deploy~~
- [x] Example for JSX <https://nanojsx.github.io> #30 
- [x] Chainable route
- [x] ~~Return method not allowed~~
- [x] ~~base path~~
- [x] Support middleware
- [x] ~~TypeScript~~ ~~make`d.ts`~~ JSDoc
- [x] TypeScript #21 
- [x] Try on TypeScript **It works!**
- [x] ~~mimify~~ **Later**
- [x] ~~SSR with assetKV~~
- [x] Error handling
- [x] Error log
- [x] Custom Error message
- [x] Error handling - Middleware should be async function
- [x] ~~redirect~~
- [x] ~~c.respond~~
- [x] ~~``app.use(router.routes());`~~
- [x] multi middleware
- [x] Test with `edge-mock`  #18 
- [x] Contribution Guide
- [x] Add keywords to package.json
- [x] Documentation
- [x] ~~Config~~
- [x] return JSON `c.json()`
- [x] `files` field in package.json 
- [x] Cloudflare Durable Objects
- [x] Cloudflare KV #60 
- [x] ~~Render HTML with template engine~~ Use JSX SSR
- [x] Content-Length
- [x] Lint #27 
- [ ] Promotion
- [x] ~~More practical example~~
- [x] example serving static #61 
- [x] Try test with [miniflare2](https://miniflare.dev/testing/jest)
- [x] `c.redirect` #36 
- [x] Support [Module Workers](https://blog.cloudflare.com/workers-javascript-modules/)?
- [x] ~~`c.notFound`~~ use `c.text('not found', 404)`
- [x] `c.json({}, 200, {'x-custom-header': 'value'})` #34 
- [ ] Development / Production... mode?
- [x] `FetchEvent` instance as `c.req.event`
- [ ] How to test app [example](https://github.com/yusukebe/hono/blob/master/examples/blog/src/controller.test.ts)
- [ ] Try esbuild
- [x] ~~`c.notFound()` ?~~
- [ ] websockets
- [x] `const res = c.text('a'); res.headers.set()` is good way? #62 

---

Middleware

- [x] Logger #11 
- [x] Basic Auth #28 
- [x] CORS #53 
- [x] body-parse #38 
- [x] ~~X-Response-Time~~
- [x] Cookie #64

**Comment by metrue** [comment]
I really want to help on the "Logger" middleware task, would you describe a little more on it?

**Comment by yusukebe** [comment]
Hey @metrue 

Thank you for your proposal, but API design for middleware is obscure. I'm still thinking about it. Please wait a moment!

**Comment by metrue** [comment]
Hi @yusukebe 

I can help on the "Basic Auth" if you're not working on it now

**Comment by yusukebe** [comment]
Hi @metrue 
Thank you! I want you help on writing the "Basic Auth". But now, I'm rewriting the code to migrate from JavaScript to TypeScript (Yes, TypeScript!!) If you can, please wait a moment writing the code. If it is done, I will mention to you.

**Comment by yusukebe** [comment]
Hi @metrue 
Migrating to TypeScript is done! If you want, please write the code of Basic Auth middleware.

**Comment by metrue** [comment]
@yusukebe yeah, PR is on the way 👨🏻‍💻

And I think it'd be great we setup a lint script for the codes to enforce a consistent code style.

**Comment by yusukebe** [comment]
@metrue 
It's not so important. I forgot meaning of the topic:( Please ignore.

**Comment by metrue** [comment]
For the middleware 'X-Response-Time', the logger middleware already included the response time information.

**Comment by yusukebe** [comment]
@metrue 
Yes. I think it's not necessary. We don't need to implement  it.

**Comment by yusukebe** [comment]
Almost don!! To be continue ... => #68
