### ISSUE TITLE
TODO 2

### ISSUE THREAD

**Issue by yusukebe** [yusukebe/hono#68]
## Routing

- [x] Deprecate chained route? #105 
- [x] Support nested(like) routing? #105 
- [x] One handler
- [x] noMatch
- [ ] `RegExpRouter` as default?

---

- [ ] Web sites?
- [x] Stacktrace #158 
- [x] Fix API
- [ ] Promotion
- [ ] How to test app / [example](https://github.com/yusukebe/hono/blob/master/examples/blog/src/controller.test.ts)
- [x] Add project template to [Cloudflare QuickStart](https://developers.cloudflare.com/workers/get-started/quickstarts)
- [x] ~~Web Sockets~~
- [x] ~~Determine Cloudflare or Compute@Edge or not~~
- [x] Dynamic import / lazy load third party modules if really want to use some Middleware
- [x] Image logo #153 
- [ ] Documentation #71 
- [ ] README
- [x] Document in Japanese #131 
- [x] Badges on README 68baca09492ba5b4fef057b247c3285887a99626
- [x] View
- [x] slurp content from files in KV #72 
- [x] ~~source map~~
- [x] ~~uglify~~
- [x] custom error object #111 
- [x] app.onError #111 
- [x] Customize error message #111 
- [x] ~~DEBUG flag?~~
- [x] Error handling: => `app.get('/', (c) => 'Hello Hono!')` 
- [x] ~~Debugging`~~
- [x] ~~Redirect trailing slash?~~
- [x] ~~Return method not allowed~~
- [x] ~~`c.stash` ?~~
- [x] ~~`405 method not allowed`~~
- [x] ~~`c.render` with other middleware~~
- [x] ~~Obsolete `chained route` and `c.route` ??~~
- [x] `TypeError: c.req.header is not a function`
- [x] ~~Cache-Control for serve-static~~
- [x] set HTTP statusText automatically
- [x] Fix examples #101 
- [x] Durable Objects example
- [x] ~~Benchmark for Compute@Edge~~
- [x] ~~Rewrite test for blog. Using [jest-miniflare](https://miniflare.dev/testing/jest)~~
- [x] ~~Do not include tests into NPM package?~~
- [x] `pretty` option on `c.json` #150 
- [x] About TypeScript in Japanese README
- [x] ~~`types.ts`~~
- [x] Directory structure

## Middleware

- [x] Serve Static for Cloudflare ~~`cf-static`~~ `serve-static` #76 
- [x] Basic Auth support Compute@Edge? #86 
- [x] Basic auth support multiple users #112 
- [x] throw error if basic auth user/pass is not set #112 
- [x] ~~Favicon ?~~
- [x] ~~compress~~
- [x] Etag #119 
- [x] GraphQL
- [x] View with `mustache` #72 
- [x] ~~View with `React`~~
- [x] ~~Stack trace~~
- [x] ~~logger use `waituntil`?~~
- [x] ~~`parsedBody` as any?~~
- [x] stack trace in `graphql`

## Not sure

- [x] ~~Development / Production mode?~~
- [x] ~~Try esbuild~~

**Comment by yusukebe** [comment]
Almost done!! To be continue ... => https://github.com/yusukebe/hono/issues/166
